### ISSUE TITLE
Run Button

### ISSUE THREAD

**Issue by crtorreg** [kapoorlab/vollseg-napari#2]
Hi, 

I am trying to use the vollseg-napari plugin but I am not able to click on run. Why might this be happening?

![image](https://user-images.githubusercontent.com/86312162/151333911-dad94338-513b-4bef-8548-646e84c97728.png)

Best, 
Cristina

**Comment by kapoorlab** [comment]
Hi Cristina,

Do you have 2 time points in this image, then the image axes should be TZYX instead of ZTYX. If something appears red in the panel it means the choices are not valid. For example look at my panel that I have when using unet and denoising model, pull the repo again as I just made some changes and they work well for your type of images. ALso these pre trained models are for ascadian embryos so they wont work well with the image that you have. Also pip install the latest version of vollseg that I relmeased a few minuets ago (2.8.5). Let me know if the program works this time, also you may want to increase the tiles to (1,4,4,4) to avoid it going out of memory. Run button will appear when all your choices are valid, image axes matching with the model axes, etc

**Comment by kapoorlab** [comment]
Did it work for you now? I released a version 2.0.1 where things should be working fine with the run button being activated by valid choices.
